baseURL = "https://zbeegnew.dev"
theme = "risotto"
title = "zbeegnews blog"
author = "Zbigniew Tomanek"
copyright = "Zbigniew Tomanek"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
enableEmoji = true

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[params]
noindex = false
custom_css = ["css/custom.css", "css/typography.css"]

[params.theme]
palette = "gruvbox-dark"

# Sidebar: about/bio
[params.about]
title = "zbeegnews blog"
description = "Reverse Engineering Reality"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/ZbigniewTomanek"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:tomanek@zbeegnew.dev"

[[params.socialLinks]]
icon = "fa-brands fa-linkedin-in"
title = "LinkedIn"
url = "https://linkedin.com/in/zbigniew-tomanek-0a14831b9"

[params.pgp]
title = "PGP Key  "
icon = "fa fa-key"
key = """
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBGSlcusBEADluxAn+6m/XA4lVU4CTMSMc7h6yXqop4EV9jwnlLGyf07leIr+
vUq948yjZbjL3eHVBDlD6ujfmY6LcPjBxQKyQaFVIro3trt11MYav03BxMLa943r
sjF6xo7kgnsiF6oGeEMOlv0v52s+rYBWOTgjmheIUfO0YO6j6QevrMekAoDRwN/q
GmCAj862BcOQTsf9HvU9EVQdkcINIrbnaj8ozWlvewi51XGUKlVV1geCsFGeuF8j
qVNPy7gqnA/4O9pnWcyND7ZZqI1bIIVEJ8+ewlyccCbt4TSEUnA2PPCVgYMDRtdS
tAi0Nk7fAFqXML2lVrTM8B80zh8Gg9Vz9V1uqzQyvdHibsr21tSiHUZJxScvi4Nu
PHW16CPBNX604eblB0/Y60S+nwsHF3qZDLqwvXp088v8CiJUbwC3FqzwvUa2ShCo
HzvGLNysPeTFbSP3RVpETFmU9z1T+B7c87eY7nB3TaY/K+kFo1MPfvT8mXT59nj7
1BZlm/Zmz0l6oIydUGZ2KhJswrCBNi8p0QyM9gqD1DYu7KVeDWr+LqUu5Gy8K0dY
llMtQls5ILx9FyGxgSQNHxZZ3lBqog0EX+9ZZhFYrJjSD7nqTDFZlELHRynfgCq+
W8UAMIj/Qx33/Oq2DRgWQCndQ45V5HCK2RC7yt+Pdq6kX4VS7srvqrW4AwARAQAB
tCdaYmlnbmlldyBUb21hbmVrIDx0b21hbmVrQHpiZWVnbmV3LmRldj6JAlEEEwEI
ADsWIQRuwV2dggmLufx6KARR0x3qluqKzwUCZKVy6wIbAwULCQgHAgIiAgYVCgkI
CwIEFgIDAQIeBwIXgAAKCRBR0x3qluqKzyiTD/9AmuYIqFSQhj5uKGO3U/SRFSZ4
4nQZt0pqawTDmG92QOb1QzLwvihrTpJ4+OrLstFASO23lwoGJtTOXUb2tM9738by
peqVZKnWJ5uXPj0CiUyr4Xz1z0Mv+RO11l0GKx61nT7e+sjLpHAh2eLdRKC/J1pe
xc9WwRqqU6szNMNKW+FDw/GyM6024yTDxwVXvZp+ln3E7ENzBR2qmZD73f4Bs6LN
68RpwpwmomBqAqPasilXqrj4RFPw49kBALlr5Uj1yXMShmMigdaC0ALKQolVPyLV
MVPpwIbnxBJUrFlYfSCM5aCoPIxk+Md9Smk7CkycKPpP6M/ushr70DrRXGiKtdZV
14X7j510KXqBZSgEsYu8dgRmnbOKhKJP7Ixf2kbVMXqu5WwaHCYF1y+i8ugPg2eX
ppvMThZJPL3oVtl3eh1kC0XHyNpqbhImutNLaErgtPy0igy/OIyrOpactNcRO5mo
i6UaJu4pwqecYz0NdMkVDbg76G3loDFT1CtLQCYqv0q9/aaWO31+MC9Cv61YlljG
9lHRD0349Ks4cK7VKDsX/KLh18W5XqOMX3pV+QWgkYqmKGPuGQ5dGnD4ydPr9Y/n
QwT2I8hgAME6+nby57B6UE3eowB7U1UrY5eSWcz1j66nchFLv3S0dMZUKmyISDy0
LdVjDho/6LbHkTp/e7kCDQRkpXLrARAAuM7MW0w+Oq47gzoNfVApeWTivA5y4dqd
lGoMy46Lgmw7gQ+IwfXpn8gs+8ZNwi5mRRi+9WMXWO4Xx4X2WIgN/TsmR6Ju3kjF
j6lA5GdZGW5fbTRwXYdAiiVR4IC2SIl57wDsUy19+Q1q252o1EbylM+VSoeenGY+
2fPraaugqVVJy/vL0bi8e7H8EmuEb5sMZI20MjRzmujsDPfugtKCjuuBHwkyPlbr
/O46VS0dQ20RnANKtEbxfKj8ppHOBEcshdhIk81OSt219Wx6+tZ820eufm3uJJbp
6oEGCUQmClU2e3gQqdJ0scUCMnV03R0viWdhacTGV9+wyvoUI24/NS7NLqKjp2TC
i7eiq/BhUdEpvAPHvOBwRcQ4v/gY0vwSUBaShfrk8KhkzJNsbos8dUTOEPgt/QeT
fChY+vXEgm+NbO38OQE7D7rRdSZRhU4k6BApI0Iyyhu2W7jV2WpmqPtFtiL3jVWG
BtwZBdy6DBfgUJnFk5GpMFOne0vFLhbGxxK7WDse8P1M0LU0i2JAXjmX486orIZA
w+kIlqPXmYNnU434OPvmn3vwvbflZWn5FAqTqFzi/ITj4hk35jD6Q9tl4FmZooXA
BP/LUylqQoR4KLo9FlrXN5xIVT1n2Z31b+J95hqvnUKBAENgIpELB4qM5BSkEdrD
L5UsSAZdGf8AEQEAAYkCNgQYAQgAIBYhBG7BXZ2CCYu5/HooBFHTHeqW6orPBQJk
pXLrAhsMAAoJEFHTHeqW6orPWfcQAIZ9m0DYiUa5A/tRI0/y44FczeOL+f42Gtub
eCB5gZuuVUbZ4xei/SnhtM7RQ0r7ZdnnsNR/chN6JLa+9AylRASuyooGZbynogoH
NDxIRVjJ1xEP3FzOSiDlqzy+8mTLnOcyHKn+GWggbRdwxV7OO6zt+iQeGpHOspca
5Q4II56xEXU4IW96y+xZMAa62hk94gdR97yznugGpnY/GUx4n4Y5eqALlxVs0dLs
ApNcklcU8OCW7G5I98Ik7woXRRhtI9cA+P1IADhjpV3ipXQ3+ACSSilP5JcjJhZd
fTJzhzEWYg95lX4kLCIOtzRLBGJUIhfm/lCNA/3nX7R4HCC2fZsdyIrr2NPR9fbf
JP0gpAuyms+li3jQ+j9hQJvagGi/4iTjm7czjgm7fiVCwtlKBwVoW9boRFCEcKDi
hVVnyZAZwJi+LjuO904O1tsxGHoyraOyfSup1v8kbR3bw96D03SZt/V62+PC373K
HH4ayjJRWm2VNHf2C7cvZdW/dTfdrsH6fe2eGIctI5AS0KjQrHb4M5EDYPH2uoJ3
iefiftd/2k4OowRFe4TzsHysNy7PBDmpI8bOXx5Or2Cy7mt5MR2a6K2vIg0k/5Nt
HEBmkclZBi+N9XWjomskCIbRMWECd8aNTDEmWYYEqdjyNpNKgDFFL0XO+KzOv3M2
ZAVUCNZA
=IuWS
-----END PGP PUBLIC KEY BLOCK-----
"""

[menu]


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]

  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
